name: Build and Publish 
run-name: ${{ github.actor }} is building and publishing
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  Build-and-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Using Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: NPM Install
        run: npm install
      - name: Build App
        run: npm run build
      - name: Clear the dist folder in S3
        run: aws s3 rm s3://${{ vars.S3BUCKETNAME }} --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
      - name: Upload dist to S3
        run: aws s3 cp ./dist s3://${{ vars.S3BUCKETNAME }} --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
